# Generated by Django 5.1.6 on 2025-02-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundkit',
            name='preview_audio',
            field=models.FileField(default='null', upload_to='soundkits/previews/'),
            preserve_default=False,
        ),
    ]
