# Generated by Django 5.1.6 on 2025-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
