# Generated by Django 5.1.6 on 2025-02-12 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_beat_likes_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='price',
        ),
        migrations.AddField(
            model_name='beat',
            name='co_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_beats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beat',
            name='main_artist',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='main_beats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beat',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Réduction en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='beat',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, help_text='Date de fin de la promotion', null=True),
        ),
        migrations.CreateModel(
            name='BeatTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la piste (Ex: Version MP3, WAV, Stems...)', max_length=255)),
                ('audio_file', models.FileField(upload_to='beats/audio/')),
                ('file_type', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('stems', 'Stems'), ('other', 'Autre')], default='mp3', max_length=50)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='beats.beat')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('license_file', models.FileField(blank=True, null=True, upload_to='licenses/files/')),
                ('terms_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='beats.beat')),
                ('tracks', models.ManyToManyField(related_name='licenses', to='beats.beattrack')),
            ],
        ),
    ]
