# Generated by Django 5.1.6 on 2025-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_remove_beat_audio_file_remove_beat_license_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Définit si le beat est public ou privé.'),
        ),
        migrations.AddField(
            model_name='beat',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Indique si le beat a été vendu en exclusivité.'),
        ),
    ]
