# Generated by Django 5.1.6 on 2025-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_beat_is_public_beat_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Indique si cette licence est exclusive.'),
        ),
    ]
