# Generated by Django 5.1.6 on 2025-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_license_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='beats/audio_files/'),
        ),
        migrations.AlterField(
            model_name='beattrack',
            name='file_type',
            field=models.CharField(choices=[('.m4a', 'AAC'), ('.opus', 'Opus'), ('.mp3', 'MP3'), ('.ogg', 'OGG'), ('.wav', 'WAV'), ('.flac', 'FLAC')], max_length=10),
        ),
    ]
