# Generated by Django 5.1.6 on 2025-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_remove_beat_user_alter_beat_main_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='beattrack',
            name='duration',
            field=models.FloatField(blank=True, help_text='Durée de la piste en secondes', null=True),
        ),
        migrations.AlterField(
            model_name='beattrack',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
