# Generated by Django 5.1.6 on 2025-02-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_beattrack_duration_alter_beattrack_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='duration',
            field=models.FloatField(blank=True, help_text='Durée de la piste sélectionnée en secondes', null=True),
        ),
    ]
