# Generated by Django 5.1.6 on 2025-02-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_beat_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='main_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_beats', to='beats.beattrack'),
        ),
    ]
