# Generated by Django 5.1.6 on 2025-02-12 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0010_beat_main_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_beats', to=settings.AUTH_USER_MODEL),
        ),
    ]
