# Generated by Django 5.1.6 on 2025-02-13 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0012_beatcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='beattrack',
            name='beat',
        ),
        migrations.RemoveField(
            model_name='license',
            name='beat',
        ),
        migrations.AddField(
            model_name='beat',
            name='licenses',
            field=models.ManyToManyField(related_name='beat', to='beats.license'),
        ),
        migrations.AddField(
            model_name='beat',
            name='tracks',
            field=models.ManyToManyField(related_name='beat', to='beats.beattrack'),
        ),
        migrations.AddField(
            model_name='license',
            name='license_template',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('UNLIMITED', 'Unlimited'), ('EXCLUSIVE', 'Exclusive'), ('RADIO', 'Radio'), ('TV', 'TV'), ('SYNC', 'Sync')], default='CUSTOM', max_length=10),
        ),
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='beats.conditions'),
        ),
        migrations.CreateModel(
            name='DraftBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('licenses', models.JSONField(blank=True, default=list, null=True)),
                ('tracks', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
