# Generated by Django 5.1.6 on 2025-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0013_conditions_remove_beattrack_beat_remove_license_beat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbeat',
            name='co_artists',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='beats/covers/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Définit si le beat est public ou privé.'),
        ),
        migrations.AlterField(
            model_name='draftbeat',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
