# Generated by Django 5.1.6 on 2025-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0014_draftbeat_co_artists_draftbeat_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beattrack',
            name='audio_file',
            field=models.FileField(upload_to='beats/audio-track/'),
        ),
        migrations.AlterField(
            model_name='draftbeat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='draft/covers/'),
        ),
        migrations.RemoveField(
            model_name='draftbeat',
            name='licenses',
        ),
        migrations.AlterField(
            model_name='draftbeat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='draftbeat',
            name='tracks',
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='licenses',
            field=models.ManyToManyField(to='beats.license'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='tracks',
            field=models.ManyToManyField(to='beats.beattrack'),
        ),
    ]
