# Generated by Django 5.1.6 on 2025-02-13 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0015_alter_beattrack_audio_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbeat',
            name='co_artists',
        ),
        migrations.AlterField(
            model_name='draftbeat',
            name='licenses',
            field=models.ManyToManyField(blank=True, to='beats.license'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='co_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_draft_beats', to=settings.AUTH_USER_MODEL),
        ),
    ]
