# Generated by Django 5.1.6 on 2025-02-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0016_remove_draftbeat_co_artists_alter_draftbeat_licenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbeat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='draft/audio_files/'),
        ),
    ]
