# Generated by Django 5.1.6 on 2025-02-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0015_alter_draftbeat_cover_image_alter_draftbeat_title'),
        ('beats', '0017_draftbeat_audio_file'),
    ]

    operations = [
    ]
