# Generated by Django 5.1.6 on 2025-02-14 10:01

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0018_remove_license_license_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_file_type',
        ),
        migrations.AddField(
            model_name='license',
            name='license_file_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('flac', 'FLAC'), ('stems', 'STEMS'), ('zip', 'ZIP')], max_length=22, null=True),
        ),
    ]
