# Generated by Django 5.1.6 on 2025-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0019_remove_license_license_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='condition',
        ),
        migrations.AddField(
            model_name='license',
            name='conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='license',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='licenses', to='beats.beattrack'),
        ),
    ]
