# Generated by Django 5.1.6 on 2025-02-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0018_merge_20250213_2110'),
        ('beats', '0019_remove_license_license_file_type_and_more'),
    ]

    operations = [
    ]
