# Generated by Django 5.1.6 on 2025-02-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0020_remove_license_condition_license_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='beats.beattrack'),
        ),
    ]
