# Generated by Django 5.1.6 on 2025-02-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0020_remove_license_condition_license_conditions_and_more'),
        ('beats', '0021_alter_license_tracks'),
    ]

    operations = [
    ]
