# Generated by Django 5.1.6 on 2025-02-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0020_merge_20250214_1011'),
        ('beats', '0022_merge_20250214_1028'),
    ]

    operations = [
    ]
