# Generated by Django 5.1.6 on 2025-02-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0023_merge_20250214_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='beats', to='beats.hashtag'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='draftbeats', to='beats.hashtag'),
        ),
    ]
