# Generated by Django 5.1.6 on 2025-02-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0025_beat_is_free_collaborationinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationinvite',
            name='beat',
        ),
        migrations.AddField(
            model_name='collaborationinvite',
            name='draftbeat',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='beats.draftbeat'),
            preserve_default=False,
        ),
    ]
