# Generated by Django 5.1.6 on 2025-02-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0026_remove_collaborationinvite_beat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beattrack',
            name='beat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='beats.beat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beat',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='beats', to='beats.beattrack'),
        ),
        migrations.CreateModel(
            name='BeatView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_views', to='beats.beat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='view_beat', to='beats.beatview'),
        ),
        migrations.AddConstraint(
            model_name='beatview',
            constraint=models.UniqueConstraint(fields=('beat', 'user'), name='unique_user_beat_view'),
        ),
        migrations.AddConstraint(
            model_name='beatview',
            constraint=models.UniqueConstraint(fields=('beat', 'ip_address'), name='unique_ip_beat_view'),
        ),
    ]
