# Generated by Django 5.1.6 on 2025-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0027_beattrack_beat_alter_beat_tracks_beatview_beat_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beattrack',
            name='beat',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='main_track',
        ),
        migrations.RemoveField(
            model_name='license',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='draftbeat',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='tracks',
        ),
        migrations.DeleteModel(
            name='Conditions',
        ),
        migrations.AlterModelOptions(
            name='beat',
            options={'verbose_name': 'Beat', 'verbose_name_plural': 'Beats'},
        ),
        migrations.RemoveField(
            model_name='beat',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='draftbeat',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='draftbeat',
            name='is_public',
        ),
        migrations.AddField(
            model_name='beat',
            name='aac',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='alac',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='flac',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='ogg',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='wav',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='zip',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='aac',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='alac',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='flac',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='ogg',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='wav',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='draftbeat',
            name='zip',
            field=models.FileField(blank=True, null=True, upload_to='beats/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='beats/audio_file'),
        ),
        migrations.DeleteModel(
            name='BeatTrack',
        ),
    ]
