# Generated by Django 5.1.6 on 2025-02-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0028_remove_beattrack_beat_remove_beat_main_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='favorites_count',
            field=models.IntegerField(default=0),
        ),
    ]
