# Generated by Django 5.1.6 on 2025-02-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0030_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='beats',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='license_type',
        ),
        migrations.AddField(
            model_name='beat',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BundleBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_beats', to='beats.beat')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_beats', to='beats.bundle')),
                ('selected_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_licenses', to='beats.license')),
            ],
            options={
                'unique_together': {('bundle', 'beat')},
            },
        ),
    ]
