// styles.js
export const STYLES = [
  // Hip Hop & Variants:
  "Hip Hop",
  "Trap",
  "Drill",
  "Boom bap",
  "Cloud rap",
  "Lo-Fi Hip Hop",
  "Experimental Hip Hop",
  "Alternative Hip Hop",
  // Electronic & Dance:
  "Electronic",
  "EDM",
  "House",
  "Techno",
  "Dubstep",
  "Drum and Bass",
  "Future Bass",
  "Phonk",
  "Brazilian Funk",
  // Chill & Atmospheric:
  "Ambient",
  "Chillhop",
  "Synthwave",
  // R&B/Pop & Crossovers:
  "RnB",
  "Neo Soul",
  "Pop",
  "Alternative", // can represent pop/rock crossover
  "Jazz Rap",
  // Regional/Urban:
  "Grime",
  "Reggae",
  "Reggaeton",
  "Latin Trap",
  "Amapiano",
];

export const EXTRA_STYLES = [
  "Alternative rnb",
  "Alternative rock",
  "Afro",
  "Afro beat",
  "Afro pop",
  "Beats",
  "Break beat",
  "Club",
  "Classical",
  "Contemporary R&B",
  "Country",
  "Country Pop",
  "Country Rap",
  "Country rock",
  "Crunk",
  "Dance",
  "Dance hall",
  "Dance rnb",
  "Dirty south",
  "Electro pop",
  "Emo Hip Hop",
  "Experimental electronic",
  "Folk",
  "Freestyle Rap",
  "Gangsta",
  "Gangsta Rap",
  "Hardcore Hip Hop",
  "Jazz",
  "Jerk",
  "Jersey Club",
  "K-pop",
  "Latin",
  "Latin pop",
  "Lo-fi",
  "Metal",
  "Metalcore",
  "Nu metal",
  "Old school",
  "Old school hip hop",
  "Orchestral",
  "Pop 80s",
  "Pop country",
  "Pop electronic",
  "Pop hip hop",
  "Pop Punk",
  "Pop rap",
  "Pop rock",
  "Pop rnb",
  "Rock",
  "Roots",
  "Rage Beats",
  "Smooth rnb",
  "Synth Pop",
  "Trip hop",
  "Two step",
  "Underground",
  "Underground Hip Hop",
  "UK grime",
  "West coast",
  "World",
];
