# Generated by Django 5.1.6 on 2025-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_invitation_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Conversation', max_length=75),
        ),
    ]
