# Generated by Django 5.1.6 on 2025-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Conversation', max_length=200),
        ),
    ]
