# Generated by Django 5.1.6 on 2025-02-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
