# Generated by Django 5.1.6 on 2025-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notifications_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
