# Generated by Django 5.1.6 on 2025-02-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notifications_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='type',
            new_name='notif_type',
        ),
    ]
