# Generated by Django 5.1.6 on 2025-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_type_notifications_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='draft_beat_title',
            field=models.CharField(default='Null', max_length=1000),
        ),
    ]
