# Generated by Django 5.1.6 on 2025-02-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0023_merge_20250214_1444'),
        ('transaction', '0002_cart_cartitem_transaction_transactionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='product_type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='license',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='beats.license'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='license',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='beats.license'),
            preserve_default=False,
        ),
    ]
